spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:13.1-alpine:///ccf
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  security:
    enabled: false
