name: Java CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: pull
      run: docker-compose pull --ignore-pull-failures
    - name: Check
      run: ./gradlew check -is
    - name: Archive test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: functionalTest/build/
